# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ім’я')),
                ('mail', models.EmailField(max_length=254, verbose_name='Поштова скринька')),
                ('mesage', models.TextField(verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name': 'Зв’язок',
                'verbose_name_plural': 'Зв’язки',
            },
        ),
    ]
